### ISSUE TITLE
Plugin must be compiled with Java 8

### ISSUE THREAD

**Issue by don-vip** [DavidKarlas/JosmReviewPlugin#1]
JOSM has still a minimal Java dependency on Java 8, thus all plugins must be compiled with Java 8 until we upgrade to Java 11 or 17.

This is not the case of this plugin, see https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.plugins/PluginHandlerTestIT/testValidityOfAvailablePlugins__/

`org/openstreetmap/josm/plugins/davidkarlas/JosmReviewPlugin/JosmReviewPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Can you please release a new version built with Java 8?

**Comment by DavidKarlas** [comment]
Sorry about that, I'm new to JOSM/Java world, I believe new version is built with JDK8, tnx for opening this issue!
