### ISSUE TITLE
Please fix the icon path in the release jar file.

### ISSUE THREAD

**Issue by stoecker** [DavidKarlas/JosmReviewPlugin#2]
The META-File does not use JOSM special handling. Please specify the icon file including the extension and also with full path (including images/ part).

If it is properly specified the icon is shown in this list (about 15 minutes after file was fixed):
https://josm.openstreetmap.de/wiki/Plugins

**Comment by DavidKarlas** [comment]
Yay! I also needed to add ".svg" at end...
![image](https://user-images.githubusercontent.com/774791/137263098-02e3a2c8-3d05-4da1-9c35-20ade57fa33f.png)
