### ISSUE TITLE
Set Manifest Property `Plugin-Minimum-Java-Version` to `17`

### ISSUE THREAD

**Issue by tsmock** [DavidKarlas/JosmReviewPlugin#4]
See https://josm.openstreetmap.de/ticket/23337 .
Alternatively, you can recompile the plugin targeting Java 8.

**Comment by DavidKarlas** [comment]
Sorry, during refactoring of Gradle files, I drop this, wishfully thinking this problem went away over last 2 years :D
https://github.com/DavidKarlas/JosmReviewPlugin/releases/tag/v1.1.1 should fix it...

**Comment by tsmock** [comment]
We have been trying to drop Java 8 support for awhile (see https://josm.openstreetmap.de/ticket/17858 ), but that hasn't happened yet.

Anyway, thank you for fixing the problem.
